language: node_js

node_js:
- '11'
- '10'
- '9'
- '8'
- '6'

script: npm test

notifications:
  email: false

cache:
  directories:
  - node_modules

addons:
  chrome: stable

dist: trusty

before_install:
  - 'if [[ `npm -v` != 5* ]]; then npm i -g npm@^5.0.0; fi'
